chore: reformat functions

diff --git a/sources/functions b/sources/functions
--- a/sources/functions
+++ b/sources/functions
@@ -2,64 +2,78 @@
 
 # create a new directory and navigate to it
 mkd() {
-	mkdir -p "$@" && cd "$_" || return
+    mkdir -p "$@" && cd "$_" || return
 }
 
 # color grep output
 grep() {
-  command grep --color=auto "$@"
+    command grep --color=auto "$@"
+}
+
+function ensure_git_repo() {
+    if ! git rev-parse --is-inside-work-tree &> /dev/null; then
+        echo "Error: Not inside a Git repository"
+        return 1
+    fi
 }
 
 # fzf git helpers
 # use fzf to find delete git branch
 function dfb() {
-  local line branch
-	line=$(git --no-pager branch -vv | fzf)
-	branch=$(echo "$line" | sed -E 's/^[* ]+([^ ]+).*/\1/')
-	
-  echo "git branch -D $branch"
-  read -p "Are you sure you want to delete this branch? [y|n] " -n 1
-  echo ""
-  
-  if [[ $REPLY =~ ^[Yy]$ ]]; then
-	  git branch -D "$branch"
-  else
-	  echo "Branch deletion aborted"
-  fi
+    ensure_git_repo || return 1
+
+    local line branch
+    line=$(git --no-pager branch -vv | fzf)
+    branch=$(echo "$line" | sed -E 's/^[* ]+([^ ]+).*/\1/')
+
+    echo "git branch -D $branch"
+    read -p "Are you sure you want to delete this branch? [y|n] " -n 1
+    echo ""
+
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
+        git branch -D "$branch"
+    else
+        echo "Branch deletion aborted"
+    fi
 }
 
 # use fzf to checkout to git branch using fuzzy finder
-function sfg() {
-	local line branch
-	line=$(git --no-pager branch -vv | fzf)
-	branch=$(echo "$line" | sed -E 's/^[* ]+([^ ]+).*/\1/')
-	git switch "$branch"
-}
-# use fzf to find a directory
-function fd() {
-  DIR=`find * -maxdepth 0 -type d -print 2> /dev/null | fzf-tmux` \
-    && cd "$DIR"
+function sfb() {
+    ensure_git_repo || return 1
+
+    local line branch
+    line=$(git --no-pager branch -vv | fzf)
+    branch=$(echo "$line" | sed -E 's/^[* ]+([^ ]+).*/\1/')
+    git switch "$branch"
 }
 
 # use fzf to rebase your branch onto a specific commit
 function gri() {
-  local line commit
-  line=$(git log --color=always --pretty=oneline --abbrev-commit | fzf --ansi --reverse)
+    ensure_git_repo || return 1
 
-  # exit the function if no commit is selected
-  if [[ -z "$line" ]]; then
-    return
-  fi
+    local line commit
+    line=$(git log --color=always --pretty=oneline --abbrev-commit | fzf --ansi --reverse)
 
-  commit=$(echo "$line" | sed -E "s/^([^ ]+).*/\1/")
+    # exit the function if no commit is selected
+    if [[ -z "$line" ]]; then
+        return
+    fi
 
-  git rebase -i "$commit"
+    commit=$(echo "$line" | sed -E "s/^([^ ]+).*/\1/")
+
+    git rebase -i "$commit"
+}
+
+# use fzf to find a directory
+function fd() {
+    DIR=$(find * -maxdepth 0 -type d -print 2> /dev/null | fzf-tmux) \
+        && cd "$DIR"
 }
 
 # to find git commit sha (very useful when using git rebase -i)
 
 # get test coverage report for go applications
-go_cover () { 
+go_cover() {
     t="/tmp/go-cover.$$.tmp"
     go test -coverprofile=$t $@ && go tool cover -html=$t && unlink $t
 }
